name: "Install psychopy"
description: "A composite action to install psychopy on linux."

runs:
  using: "composite"
  steps:
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@main
      with:
        qt: true
    - name: Install dependencies
      run: |
        python -m pip install --progress-bar off --upgrade pip setuptools
        python -m pip install --progress-bar off .[test]
        readonly wx_name="wxPython-4.2.1-cp310-cp310-linux_x86_64.whl"
        curl https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/${wx_name} -o ${wx_name}
        python -m pip install --progress-bar off ${wx_name}
        python -m pip install --progress-bar off psychopy psychtoolbox
