name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  pytest:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ["3.10"]
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Update pip and setuptools
        run: python -m pip install --progress-bar off --upgrade pip setuptools wheel
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@main
        with:
          qt: true
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip install --progress-bar off .[test]
          readonly wx_name="wxPython-4.2.1-cp310-cp310-linux_x86_64.whl"
          curl https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/${wx_name} -o ${wx_name}
          python -m pip install --progress-bar off ${wx_name}
          python -m pip install --progress-bar off psychopy psychtoolbox
      - name: Install package
        run: python -m pip install --progress-bar off .[test]
      - name: Display system information
        run: mrisim-sys_info --developer
      - name: Run pytest
        run: pytest mrisim --cov=mrisim --cov-report=xml --cov-config=pyproject.toml
      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests  # optional
          name: codecov-umbrella  # optional
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true  # optional (default = false)
